"""Audit event type taxonomy — exact strings from brief section 5.3.

All business code must import from here; no string literals allowed.
"""
from enum import StrEnum


class EventType(StrEnum):
    # Stage 0
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    FILE_HASH_COMPUTED = "FILE_HASH_COMPUTED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    SCAN_DETECTION_RUN = "SCAN_DETECTION_RUN"
    OCR_STARTED = "OCR_STARTED"
    OCR_COMPLETED = "OCR_COMPLETED"
    STRUCTURE_PARSED = "STRUCTURE_PARSED"
    TABLES_EXTRACTED = "TABLES_EXTRACTED"
    CHUNKS_PRODUCED = "CHUNKS_PRODUCED"
    EMBEDDINGS_COMPUTED = "EMBEDDINGS_COMPUTED"
    FAISS_INDEX_BUILT = "FAISS_INDEX_BUILT"
    FAISS_INDEX_REBUILT = "FAISS_INDEX_REBUILT"
    INGEST_WARNING = "INGEST_WARNING"
    SCALE_AMBIGUITY_RESOLVED = "SCALE_AMBIGUITY_RESOLVED"
    STAGE_0_COMPLETED = "STAGE_0_COMPLETED"

    # Stage 1
    DEFINITIONS_LOCATED = "DEFINITIONS_LOCATED"
    DEFINED_TERMS_EXTRACTED = "DEFINED_TERMS_EXTRACTED"
    TERM_GRAPH_BUILT = "TERM_GRAPH_BUILT"
    COVENANT_CLAUSE_CLASSIFIED = "COVENANT_CLAUSE_CLASSIFIED"
    COVENANT_EXTRACTION_STARTED = "COVENANT_EXTRACTION_STARTED"
    LLM_CALL_MADE = "LLM_CALL_MADE"
    SELF_CONSISTENCY_CHECK_RUN = "SELF_CONSISTENCY_CHECK_RUN"
    VALIDATION_CHECK_RUN = "VALIDATION_CHECK_RUN"
    AMENDMENT_APPLIED = "AMENDMENT_APPLIED"
    STAGE_1_COMPLETED = "STAGE_1_COMPLETED"
    HUMAN_GATE_OPENED = "HUMAN_GATE_OPENED"

    # Human-gate events
    RULE_APPROVED = "RULE_APPROVED"
    RULE_EDITED = "RULE_EDITED"
    RULE_REJECTED = "RULE_REJECTED"
    MAPPING_APPROVED = "MAPPING_APPROVED"
    MAPPING_OVERRIDDEN = "MAPPING_OVERRIDDEN"
    MAPPING_FLAGGED = "MAPPING_FLAGGED"
    EXCEPTION_INVESTIGATION_SAVED = "EXCEPTION_INVESTIGATION_SAVED"
    EXCEPTION_CONCLUSION_SET = "EXCEPTION_CONCLUSION_SET"
    RAG_QUERY_RUN = "RAG_QUERY_RUN"
    REVIEW_EVENT = "REVIEW_EVENT"
    WAIVER = "WAIVER"

    # Stage 2
    FIELD_REQUIREMENTS_DETERMINED = "FIELD_REQUIREMENTS_DETERMINED"
    MAPPING_ATTEMPTED = "MAPPING_ATTEMPTED"
    MAPPING_RESOLVED = "MAPPING_RESOLVED"
    EXCLUSION_RULE_APPLIED = "EXCLUSION_RULE_APPLIED"
    AGGREGATION_PERFORMED = "AGGREGATION_PERFORMED"
    LTM_RECONSTRUCTED = "LTM_RECONSTRUCTED"
    MISSING_DATA_WARNING = "MISSING_DATA_WARNING"
    STAGE_2_COMPLETED = "STAGE_2_COMPLETED"

    # Stage 3
    CALCULATION_STARTED = "CALCULATION_STARTED"
    INPUT_SNAPSHOT_HASHED = "INPUT_SNAPSHOT_HASHED"
    CIRCULAR_CAP_RESOLVED = "CIRCULAR_CAP_RESOLVED"
    RATIO_COMPUTED = "RATIO_COMPUTED"
    THRESHOLD_LOOKUP = "THRESHOLD_LOOKUP"
    COMPLIANCE_VERDICT = "COMPLIANCE_VERDICT"
    Z3_CROSS_CHECK_RUN = "Z3_CROSS_CHECK_RUN"
    STAGE_3_COMPLETED = "STAGE_3_COMPLETED"

    # Stage 4
    EXTERNAL_API_CALL_PLANNED = "EXTERNAL_API_CALL_PLANNED"
    EXTERNAL_API_CALL_MADE = "EXTERNAL_API_CALL_MADE"
    EXTERNAL_DATA_FETCHED = "EXTERNAL_DATA_FETCHED"
    THREE_WAY_MATCH_RUN = "THREE_WAY_MATCH_RUN"
    VARIANCE_DETECTED = "VARIANCE_DETECTED"
    ROOT_CAUSE_DIAGNOSED = "ROOT_CAUSE_DIAGNOSED"
    MATERIALITY_CLASSIFIED = "MATERIALITY_CLASSIFIED"
    EXCEPTION_RAISED = "EXCEPTION_RAISED"
    STAGE_4_COMPLETED = "STAGE_4_COMPLETED"

    # Stage 5
    PRE_SEAL_VALIDATION_STARTED = "PRE_SEAL_VALIDATION_STARTED"
    CHAIN_VERIFIED = "CHAIN_VERIFIED"
    SIGN_OFFS_VERIFIED = "SIGN_OFFS_VERIFIED"
    DELIVERABLES_ASSEMBLED = "DELIVERABLES_ASSEMBLED"
    MASTER_PDF_HASHED = "MASTER_PDF_HASHED"
    RFC3161_TIMESTAMP_REQUESTED = "RFC3161_TIMESTAMP_REQUESTED"
    RFC3161_TIMESTAMP_RECEIVED = "RFC3161_TIMESTAMP_RECEIVED"
    EVIDENCE_PACK_SEALED = "EVIDENCE_PACK_SEALED"
    STAGE_5_COMPLETED = "STAGE_5_COMPLETED"

    # Engagement-level
    ENGAGEMENT_CREATED = "ENGAGEMENT_CREATED"
    ENGAGEMENT_UPDATED = "ENGAGEMENT_UPDATED"
    PIPELINE_STARTED = "PIPELINE_STARTED"
    PIPELINE_RESUMED = "PIPELINE_RESUMED"
    PIPELINE_FAILED = "PIPELINE_FAILED"
